---
name: Erlang CI 1

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        erlang:
          - 26.0.2
          - 25.3.2.5
          - 24.3.4.13

    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do eunit, ct
